# Basic workflow to help you get started with Actions

name: Daily cron job

on:
  # Triggers the workflow every day at 11am PCT (1900 UTC)
  schedule:
    - cron: "15 20 * * *"
    # - cron: "*/5 * * * *" # runs every 5 minutes

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  cron:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 #install the python needed
      - name: execute scraper.py 
        env: 
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install tweepy
          pip install requests
          pip install PyGithub
          pip install tensorflow
          pip install transformers
          pip install setfit
          pip install asyncio
          pip install asyncpraw
          python code/run_scrapers.py




